main:
- name: Beranda
  pageRef: /
  weight: 10

- name: Products
  pageRef: /products
  weight: 20

- name: Batik
  parent: Products
  pageRef: /products/batik
  weight: 2

- name: Bangunan
  parent: Products
  pageRef: /products/bangunan
  weight: 3

- name: Kontak
  pageRef: /contact
  weight: 30
